### ISSUE TITLE
PgTune creates invalid configuration inside docker

### ISSUE THREAD

**Issue by dorny** [timescale/timescaledb-docker#54]
Hello,

For some reason PgTune thinks we have 8 388 608 TB of available memory.
This results in invalid configuration because some values exceeds integer range.
As of #53  it's easy to disable or override this.
Anyway I'm opening this issue to track this behavior.

Bellow is relevant part of the container output:
```
Recommendations based on 8 388 608.00 TB of available memory and 4 CPUs for PostgreSQL 11
shared_buffers = 2147483647GB
effective_cache_size = 2147483647GB
maintenance_work_mem = 2047MB
work_mem = 10737418GB
timescaledb.max_background_workers = 4
max_worker_processes = 11
max_parallel_workers_per_gather = 2
max_parallel_workers = 4
wal_buffers = 16MB
min_wal_size = 4GB
max_wal_size = 8GB
default_statistics_target = 500
random_page_cost = 1.1
checkpoint_completion_target = 0.9
max_connections = 50
max_locks_per_transaction = 512
effective_io_concurrency = 200
timescaledb.last_tuned = '2019-02-14T12:42:38Z'
timescaledb.last_tuned_version = '0.4.1'
Saving changes to: /var/lib/postgresql/data/postgresql.conf

2019-02-14 12:42:38.961 UTC [31] LOG:  received fast shutdown request
waiting for server to shut down....2019-02-14 12:42:38.963 UTC [31] LOG:  aborting any active transactions
2019-02-14 12:42:38.963 UTC [43] LOG:  terminating TimescaleDB job scheduler due to administrator command
2019-02-14 12:42:38.963 UTC [43] FATAL:  terminating connection due to administrator command
2019-02-14 12:42:38.963 UTC [46] LOG:  terminating TimescaleDB background job "Telemetry Reporter" due to administrator command
2019-02-14 12:42:38.963 UTC [38] LOG:  terminating TimescaleDB background worker launcher due to administrator command
2019-02-14 12:42:38.963 UTC [38] FATAL:  terminating connection due to administrator command
2019-02-14 12:42:38.963 UTC [43] LOG:  terminating TimescaleDB job scheduler due to administrator command
2019-02-14 12:42:38.963 UTC [46] LOG:  terminating TimescaleDB background job "Telemetry Reporter" due to administrator command
2019-02-14 12:42:38.964 UTC [46] FATAL:  terminating connection due to administrator command
2019-02-14 12:42:38.964 UTC [59] FATAL:  terminating autovacuum process due to administrator command
2019-02-14 12:42:38.965 UTC [31] LOG:  background worker "TimescaleDB Background Worker Launcher" (PID 38) exited with exit code 1
2019-02-14 12:42:38.965 UTC [31] LOG:  background worker "logical replication launcher" (PID 39) exited with exit code 1
2019-02-14 12:42:38.965 UTC [31] LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 43) exited with exit code 1
2019-02-14 12:42:38.965 UTC [31] LOG:  background worker "Telemetry Reporter" (PID 46) exited with exit code 1
2019-02-14 12:42:38.965 UTC [33] LOG:  shutting down
2019-02-14 12:42:39.092 UTC [31] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2019-02-14 12:42:39.167 GMT [1] LOG:  invalid value for parameter "shared_buffers": "2147483647GB"
2019-02-14 12:42:39.167 GMT [1] HINT:  Value exceeds integer range.
2019-02-14 12:42:39.167 GMT [1] LOG:  invalid value for parameter "work_mem": "10737418GB"
2019-02-14 12:42:39.167 GMT [1] HINT:  Value exceeds integer range.
2019-02-14 12:42:39.167 GMT [1] LOG:  invalid value for parameter "effective_cache_size": "2147483647GB"
2019-02-14 12:42:39.167 GMT [1] HINT:  Value exceeds integer range.
2019-02-14 12:42:39.168 UTC [1] FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
```

**Comment by brintal** [comment]
Exactly the same behavior here:
> Recommendations based on 8388608.00 TB of available memory and 24 CPUs for PostgreSQL 11
CPU count is correct, memory is -a bit- off :)

**Comment by RobAtticus** [comment]
Ugh, thanks for reporting this. Can either of you `docker exec` into the container and run these commands and post the output:
```
cat /sys/fs/cgroup/memory/memory.limit_in_bytes
```
and
```
free -b | grep 'Mem' | awk '{print $2}'
```

Seems like our check for the memory being too large is not working.

**Comment by LeeHampton** [comment]
@brintal Thanks for reporting this. In addition to the information requested by @RobAtticus , can you tell me if you're using the default docker image or the bitnami one?

**Comment by dorny** [comment]
We are using the default docker image.

This produces same result inside and outside the container
`cat /sys/fs/cgroup/memory/memory.limit_in_bytes`: `9223372036854771712`

`free -b | grep 'Mem' | awk '{print $2}'`:
* inside container: `1682022400015315591168`
* directly on host: `16820224000`

**Comment by RobAtticus** [comment]
Hi @dorny , one more thing then, what is the result of `free -b` by itself, inside the container? It appears that maybe two numbers are running together and our parsing needs a bit of work :)

**Comment by brintal** [comment]
Container:
```bash-4.4# cat /sys/fs/cgroup/memory/memory.limit_in_bytes
9223372036854771712
bash-4.4# free -b | grep 'Mem' | awk '{print $2}'
5061901926447790587904
bash-4.4# free -b
             total       used       free     shared    buffers     cached
Mem:   5061901926447792046080 2826973184 5736181760  34178662439221534720
-/+ buffers/cache: 822872473642390294528
Swap:   8589930496   55836672 8534093824```

Host:
```brin@myhost:~$ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
9223372036854771712
brin@myhost:~$ free -b | grep 'Mem' | awk '{print $2}'
50619019264
brin@myhost:~$ free -b
              total        used        free      shared  buff/cache   available
Mem:    50619019264  6886981632  2849935360  5736177664 40882102272 37415194624
Swap:    8589930496    55836672  8534093824```

Using default Docker Image: **timescale/timescaledb:latest-pg11**

**Comment by RobAtticus** [comment]
Yup, looks like `free -b` has the numbers running together when they are large enough so we are using the wrong value. Working on a fix, thanks for your help!

**Comment by LeeHampton** [comment]
This almost definitely seems to be a formatting issue when you have a sufficiently large string of bytes, so the solution is probably just to use MB instead. But just in case @dorny , could you also send us the host/container output of `free -m`?

**Comment by RobAtticus** [comment]
(Or @brintal )

**Comment by brintal** [comment]
Container:
```
bash-4.4# free -m
             total       used       free     shared    buffers     cached
Mem:         48274      45585       2688       5468        329      37393
-/+ buffers/cache:       7862      40411
Swap:         8191         53       8138
```

Host:
```
brin@myhost:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:          48274        6583        2708        5468       38981       35667
Swap:          8191          53        8138
```

**Comment by RobAtticus** [comment]
Assuming the output of `free -m` is reasonable, we have a PR here to fix it: #55

**Comment by RobAtticus** [comment]
Thanks @brintal , that looks safe to use then. We'll get that PR merged and release new images ASAP

**Comment by RobAtticus** [comment]
Thanks again @brintal and @dorny, I have just pushed updated images to DockerHub so if you re-pull the memory settings should make more sense now :)

**Comment by dorny** [comment]
Thanks. I can confirm it works correctly now so I'm closing the issue :)

**Comment by satshabad-cr** [comment]
Hi, I still see `cat /sys/fs/cgroup/memory/memory.limit_in_bytes: 9223372036854771712` on the latest pg-11 images. Any chance this wasn't pushed?

**Comment by RobAtticus** [comment]
@satshabad-cr So we don't change the output of `cat /sys/fs/cgroup/memory/memory.limit_in_bytes`, since we don't really control that aspect. What we do instead is if we get something like that, we use the value of `free -m` instead for tuning.

That is, even with our fix you'll still get that large number for `cat /sys/fs/cgroup/memory/memory.limit_in_bytes`, but tuning should succeed by using other values later on.

**Comment by satshabad-cr** [comment]
Ah got it, yes sadly this was all a red herring for me. Thanks!
